### ISSUE TITLE
Preparar sección para agregar contenido del evento

### ISSUE THREAD

**Issue by cesc1989** [ideaware/hacktoberfest#19]
Esta sería la sección donde los participantes agregarán, mediante PRs, imágenes de lo que ellos vivieron durante el evento.

**Comment by cesc1989** [comment]
@Mrls94 te parecería esto mejor en una página o en una sección ?

**Comment by cesc1989** [comment]
Cada bloque de contribución sería algo al estilo:

```html
<div class="experience">
  <img src="imagen" alt="texto imagen" />
  <p>Texto</p>
</div>
```

**Comment by Mrls94** [comment]
🙃 el coshi
