### ISSUE TITLE
Agregar sección observaciones

### ISSUE THREAD

**Issue by CalaoJuanPablo** [ideaware/hacktoberfest#20]
Va entre Agenda y Patrocinadores

![sección observaciones](https://user-images.githubusercontent.com/1375981/67022170-6af2d200-f0c6-11e9-94ca-33ac42ae407f.png)

**Comment by cesc1989** [comment]
¿Qué es esto @CalaoJuanPablo ?

**Comment by CalaoJuanPablo** [comment]
> ¿Qué es esto @CalaoJuanPablo ?

Es una sección que está en el diseño
