### ISSUE TITLE
Create Resources Repo

### ISSUE THREAD

**Issue by Mrls94** [ideaware/hacktoberfest#28]
Have a Repo where we can host or have link to all the different resources we are using

examples:
- Presentation slides
- Useful links
- Videos we might upload during the event

**Comment by cesc1989** [comment]
@Mrls94 y si más bien usamos la Wiki de este mismo repo?

**Comment by cesc1989** [comment]
Todo va para la Wiki https://github.com/ideaware/hacktoberfest/wiki
