### ISSUE TITLE
Quitar enlace "Detalles"

### ISSUE THREAD

**Issue by cesc1989** [ideaware/hacktoberfest#5]
Creo que mantener la _landing_ de una sola página será más conveniente

**Comment by CalaoJuanPablo** [comment]
puede ser link a la sección 'detalles' del home

**Comment by cesc1989** [comment]
@CalaoJuanPablo o sea un _anchor_?

**Comment by CalaoJuanPablo** [comment]
> @CalaoJuanPablo o sea un _anchor_?

Sí. Habría que tener en cuenta también ponerle el smooth scroll
